spring.application.name=gateway-service
server.port=8080


spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://customer-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**,/customers/**,/accounts/**,/transfers/**,/transactions/**

spring.cloud.gateway.server.webflux.routes[2].id=ledger-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://ledger-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ledger/**

spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://payment-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payments/**

logging.level.org.springframework.cloud.gateway=INFO

# Must match customer-service secret
app.jwt.secret=ChangeMe_ThisIsADevSecretKey_AtLeast32CharsLong!
